USE sakila;

-- 1. List the number of films per category.

SELECT c.name AS category, COUNT(f.film_id) AS count
FROM sakila.category AS c
JOIN sakila.film_category AS fc ON c.category_id = fc.category_id
JOIN sakila.film AS f ON fc.film_id = f.film_id
GROUP BY c.name;


-- 2. Retrieve the store ID, city, and country for each store.


select s.store_id, c.city, co.country
from sakila.store as s
join sakila.address as a on s.address_id = a.address_id 
join sakila.city as c on a.city_id = c.city_id
join sakila.country as co on c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

select  s.store_id, sum(p.amount) as total_revenue 
from sakila.payment as p
join sakila.staff as st on p.staff_id = st.staff_id
join sakila.store as s on st.store_id = s.store_id
group by s.store_id;

-- 4. Determine the average running time of films for each category.

select c.name, round(avg(f.length),2) as average_running_time 
from sakila.film as f
join sakila.film_category as fc on f.film_id = fc.film_id
join sakila.category as c on fc.category_id = c.category_id
group by c.name
order by average_running_time desc;

-- 5. Identify the film categories with the longest average running time.

select c.name, round(avg(f.length),2) as average_running_time 
from sakila.film as f
join sakila.film_category as fc on f.film_id = fc.film_id
join sakila.category as c on fc.category_id = c.category_id
group by c.name
order by average_running_time desc
limit 1;

-- 6. Display the top 10 most frequently rented movies in descending order.

select f.title, count(distinct(r.rental_id)) as count
from sakila.film as f
join sakila.inventory as i on f.film_id = i.film_id
join sakila.rental as r on i.inventory_id = r.inventory_id
group by f.title
order by count desc
limit 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.

select f.title, count(f.title) as amount_available, s.store_id
from sakila.film as f
join sakila.inventory as i on f.film_id = i.film_id
join sakila.rental as r on i.inventory_id = r.inventory_id
join sakila.store as s on i.store_id = s.store_id
where s.store_id = 1 and f.title like "%Academy Dinosaur%";
